/Users/song-yeejun/.local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator OneHotEncoder from version 0.24.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/Users/song-yeejun/.local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator Pipeline from version 0.24.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5002
 * Running on http://192.168.219.100:5002
Press CTRL+C to quit
 * Restarting with watchdog (fsevents)
/Users/song-yeejun/.local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator OneHotEncoder from version 0.24.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/Users/song-yeejun/.local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator Pipeline from version 0.24.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
 * Debugger is active!
 * Debugger PIN: 114-638-911
/Users/song-yeejun/.local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator OneHotEncoder from version 0.24.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/Users/song-yeejun/.local/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator Pipeline from version 0.24.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
 * Serving Flask app 'app'
 * Debug mode: on
Address already in use
Port 5002 is in use by another program. Either identify and stop that program, or start the server with a different port.
Traceback (most recent call last):
  File "/Users/song-yeejun/Desktop/smart_health_lab/development/Calculators/kt_donor_calculator/server/app.py", line 131, in <module>
    app.run(host='0.0.0.0', port=5002, debug=True)
  File "/Users/song-yeejun/opt/anaconda3/lib/python3.8/site-packages/flask/app.py", line 1191, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Users/song-yeejun/opt/anaconda3/lib/python3.8/site-packages/werkzeug/serving.py", line 1059, in run_simple
    run_with_reloader(
  File "/Users/song-yeejun/opt/anaconda3/lib/python3.8/site-packages/werkzeug/_reloader.py", line 434, in run_with_reloader
    ensure_echo_on()
  File "/Users/song-yeejun/opt/anaconda3/lib/python3.8/site-packages/werkzeug/_reloader.py", line 414, in ensure_echo_on
    termios.tcsetattr(sys.stdin, termios.TCSANOW, attributes)
termios.error: (4, 'Interrupted system call')
